### ISSUE TITLE
aliases are ignored on vagrant 1.7.4

### ISSUE THREAD

**Issue by ivoputzer** [cogitatio/vagrant-hostsupdater#72] opened 2015-09-10 10:26 UTC
it looks like that on vagrant 1.7.4 the hostname gets inserted correctly into the `/etc/hosts` file though the aliases are just ignored upon vagrant startup instructions.

**Comment by cgsmith** [comment] 2015-10-28 01:07
@ivoputzer I don't see an issue running with Vagrant 1.7.4 on Ubuntu 14.04.

Can you provide a sample of what your Vagrantfile looks like?

**Comment by cgsmith** [comment] 2016-01-15 02:17
Closing - I have not been able to reproduce this issue.

**Closed by cgsmith** 2016-01-15 02:17 UTC
Labels: question
